[component]
array_structures = ["content_blocks"]
label="Info"
description="Generic info section"
icon="info_outline"
tags=["content"]

[props]
bg = true
left = false
text_markdown = "This is some text about components. About this sort of length with a few sentences."
