[component]
array_structures = ["content_blocks"]
label="Code Block"
description="Editable code block"
icon="code"
tags=["content", "interactive"]

[props]
code_block = """[component]
array_structures = ["content_blocks"]
label="Header"
description="Main page h1"
icon="psychology"
tags=["headings", "structure"]"""
