[meta]
array_structures = ["content_blocks"]
label="Piccy"
description="Generic info with picture"
icon="filter_hdr"
tags=["content"]

[defaults]
flip = false
pin_to_width = false
text_markdown = "This is some text about components, with a picture."

[defaults.pic]
image = "/assets/sheepdog.svg"
alt = "Sheepdog"


[standard]

[flip]
flip = true




