title: Static Site Components
email: liam@cloudcannon.com
description: >-
  Static Site Components all hands website

baseurl: ""
url: ""

bookshop_locations:
  - ../components

plugins:
  - jekyll-bookshop
  - bookshop-array-structures
  - jekyll-postcss


twitter_username: liambigelow
github_username:  bglw

_select_data:
  alignments:
    - pinned
    - center
    - top
    - bottom
  bg_colors:
    - white
    - light
    - dark

_array_structures:
  content_blocks:
    style: modal
  page_sections:
    values:
      - label: Page Section
        icon: crop_7_5
        value:
          slug:
          bg_color: white
          alignment: center
          content_blocks:
