title: Static Site Components
email: liam@cloudcannon.com
description: >-
  Static Site Components all hands website

baseurl: ""
url: ""

plugins:
  - jekyll-bookshop
  - jekyll-stretcher
  - bookshop-array-structures
  - jekyll-svelte-slabs

twitter_username: liambigelow
github_username:  bglw

theme: theme

_select_data:
  alignments:
    - pinned
    - center
    - top
    - bottom
  bg_colors:
    - white
    - light
    - dark

_array_structures:
  content_blocks:
    style: modal
  page_sections:
    values:
      - label: Page Section
        icon: crop_7_5
        value:
          label:
          bg_color: white
          alignment: center
          content_blocks:
