source "https://rubygems.org"

gem "jekyll", "~> 4.1.1"
gem "toml-rb", "~> 2.0"
gem "theme", :path => '../theme'

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-watch", :git => "https://github.com/cloudcannon/jekyll-watch", :branch => "master"
  gem 'jekyll-stretcher', "~> 0.1"
  gem "jekyll-bookshop", "~> 1.4"
  gem "jekyll-svelte-slabs", "~> 0.0.2"
  gem "bookshop-array-structures", "~> 1.4.7"
end