[component]
array_structures = ["content_blocks"]
label="Piccy"
description="Generic info with picture"
icon="filter_hdr"
tags=["content"]

[props]
flip = false
pin_to_width = false
text_markdown = "This is some text about components, with a picture."

[props.pic]
image = "/assets/sheepdog.svg"
alt = "Sheepdog"

