[meta]
array_structures = ["content_blocks"]
label="Code Block"
description="Editable code block"
icon="code"
tags=["content", "interactive"]

[defaults]
code_block = """[meta]
array_structures = ["content_blocks"]
label="Header"
description="Main page h1"
icon="psychology"
tags=["headings", "structure"]"""

[standard]



