[meta]
array_structures = ["content_blocks"]
label="Navigation"
description="Page navigation"
icon="more_horiz"
tags=["structure"]

[defaults]

[defaults.logo]
image = "/assets/me.png"
alt = "Me, but angry"

[defaults.links--repeat]
title = "Tree"
href = "#tree"

[standard]



